#!/usr/bin/env python3
"""
Task 5.5.5 — Flow-Weighted Link Refinement

Augment the Delaunay-based regional hub network with region-to-region freight
interaction data from Task 1. Apply a hybrid rule:

1. Start from Delaunay + shared-region links generated by Task 5.5.
2. Compute hub-pair freight intensity from internal NE region-to-region flows.
3. Prune links that are both low-flow and long-distance.
4. Add missing high-flow links within the operational distance cap.

Inputs
------
Data/Task5/task5_hub_network_links.csv
Data/Task5/selected_hubs.csv
Data/Task1/raw.parquet
Data/Task3/outputs/region_assignment.csv

Outputs
-------
Data/Task5/task5_hub_network_links_flow_weighted.csv
Data/Task5/cache/region_flow_matrix.parquet
"""

from __future__ import annotations

import warnings
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
from pyproj import Transformer

warnings.filterwarnings("ignore")


ROOT = Path(__file__).resolve().parent.parent
DATA_T1 = ROOT / "Data/Task1"
DATA_T3 = ROOT / "Data/Task3"
DATA_T5 = ROOT / "Data/Task5"
CACHE = DATA_T5 / "cache"

BASE_LINK_PATH = DATA_T5 / "task5_hub_network_links.csv"
FLOW_LINK_PATH = DATA_T5 / "task5_hub_network_links_flow_weighted.csv"
REGION_FLOW_CACHE = CACHE / "region_flow_matrix.parquet"

MAX_LINK_MILES = 350.0
FLOW_SUPPLEMENT_THRESHOLD_PERCENTILE = 75


def _require_inputs() -> None:
    missing = [
        path
        for path in [
            BASE_LINK_PATH,
            DATA_T5 / "selected_hubs.csv",
            DATA_T1 / "raw.parquet",
            DATA_T3 / "outputs/region_assignment.csv",
        ]
        if not path.exists()
    ]
    if missing:
        missing_text = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(
            "Missing required Task 5 flow-weighted link inputs:\n"
            f"{missing_text}\n\n"
            "Generate the baseline Delaunay link file from Task 5.5 before "
            "running this refinement script."
        )


def _parse_regions_served(value: object) -> list[int]:
    if pd.isna(value):
        return []
    return [int(region_id) for region_id in str(value).split(";") if str(region_id) != ""]


def load_region_flows() -> pd.DataFrame:
    """Load or compute the cached 50x50 region-to-region flow matrix."""
    if REGION_FLOW_CACHE.exists():
        print(f"  [CACHE HIT] Loading {REGION_FLOW_CACHE}")
        return pd.read_parquet(REGION_FLOW_CACHE)

    print("  [CACHE MISS] Computing region flows from Task 1 raw.parquet")
    flows_raw = pd.read_parquet(DATA_T1 / "raw.parquet")
    print(f"    Raw flows: {len(flows_raw):,} rows")

    flows = flows_raw[~flows_raw["sctgG5"].isin(["sctg1014", "sctg1519"])].copy()
    print(f"    After commodity filter: {len(flows):,} rows")

    region_assign = pd.read_csv(DATA_T3 / "outputs/region_assignment.csv")
    fips_to_region = dict(
        zip(
            region_assign["fips"].astype(str).str.zfill(5),
            region_assign["region_id"],
        )
    )
    print(
        "    County-to-region map: "
        f"{len(fips_to_region)} counties -> {region_assign['region_id'].nunique()} regions"
    )

    flows["origin_region"] = (
        flows["origin_county_fips"].astype(str).str.zfill(5).map(fips_to_region)
    )
    flows["dest_region"] = (
        flows["dest_county_fips"].astype(str).str.zfill(5).map(fips_to_region)
    )

    flows_internal = flows[
        flows["origin_region"].notna() & flows["dest_region"].notna()
    ].copy()
    print(f"    Internal NE flows: {len(flows_internal):,} rows")

    region_flows = flows_internal.groupby(
        ["origin_region", "dest_region"], as_index=False
    )[["tons_2025", "tons_2030"]].sum()

    # Store a symmetric lookup table so every ordered pair has the bidirectional
    # region-pair total. This matches the flow-intensity logic used for Task 5.
    region_flows_rev = region_flows.copy()
    region_flows_rev.columns = [
        "dest_region",
        "origin_region",
        "tons_2025",
        "tons_2030",
    ]
    region_flows = pd.concat([region_flows, region_flows_rev]).groupby(
        ["origin_region", "dest_region"], as_index=False
    ).sum()

    CACHE.mkdir(parents=True, exist_ok=True)
    region_flows.to_parquet(REGION_FLOW_CACHE, index=False)
    print(f"    Cached to {REGION_FLOW_CACHE}")
    return region_flows


def compute_hub_pair_flow(
    h_a_idx: int,
    h_b_idx: int,
    hub_lookup: dict[int, list[int]],
    flow_lookup: dict[tuple[int, int], float],
) -> float:
    """Sum bidirectional 2025 flow between all regions served by two hubs."""
    total_flow = 0.0
    for r_a in hub_lookup.get(h_a_idx, []):
        for r_b in hub_lookup.get(h_b_idx, []):
            total_flow += flow_lookup.get((r_a, r_b), 0.0)
            total_flow += flow_lookup.get((r_b, r_a), 0.0)
    return float(total_flow)


def main() -> None:
    print("=" * 80)
    print("Task 5.5.5 — Flow-Weighted Link Refinement")
    print("=" * 80)

    _require_inputs()

    print("\n[1/6] Loading baseline links and selected hubs")
    links_df = pd.read_csv(BASE_LINK_PATH)
    hubs_df = pd.read_csv(DATA_T5 / "selected_hubs.csv")
    hubs_df["regions_served"] = hubs_df["regions_served"].apply(_parse_regions_served)
    hub_lookup = hubs_df.set_index("h_idx")["regions_served"].to_dict()
    hub_meta = hubs_df.set_index("h_idx")
    print(f"  Baseline links: {len(links_df)}")
    print(f"  Selected hubs: {len(hubs_df)}")

    print("\n[2/6] Loading region-to-region flow matrix")
    region_flows = load_region_flows()
    print(f"  Region-pair rows: {len(region_flows):,}")
    print(
        "  Flow range: "
        f"{region_flows['tons_2025'].min():.0f} - "
        f"{region_flows['tons_2025'].max():.0f} thousand tons"
    )

    flow_lookup = dict(
        zip(
            zip(region_flows["origin_region"], region_flows["dest_region"]),
            region_flows["tons_2025"],
        )
    )

    print("\n[3/6] Computing flow intensity for baseline links")
    links_df["flow_intensity"] = links_df.apply(
        lambda row: compute_hub_pair_flow(
            int(row["hub_a_h_idx"]),
            int(row["hub_b_h_idx"]),
            hub_lookup,
            flow_lookup,
        ),
        axis=1,
    )
    print(links_df["flow_intensity"].describe().to_string())

    print("\n[4/6] Pruning links with low flow and long distance")
    flow_p10 = links_df["flow_intensity"].quantile(0.10)
    dist_p70 = links_df["distance_miles"].quantile(0.70)
    prune_mask = (
        (links_df["flow_intensity"] < flow_p10)
        & (links_df["distance_miles"] > dist_p70)
    )
    pruned_links = links_df[prune_mask].copy()
    kept_links = links_df[~prune_mask].copy()
    print(f"  Flow 10th percentile: {flow_p10:,.0f} thousand tons")
    print(f"  Distance 70th percentile: {dist_p70:.1f} miles")
    print(f"  Pruned links: {len(pruned_links)}")
    print(f"  Kept links: {len(kept_links)}")

    print("\n[5/6] Adding missing high-flow links within distance cap")
    transformer = Transformer.from_crs("EPSG:4326", "EPSG:9311", always_xy=True)
    hub_coords = {}
    for _, row in hubs_df.iterrows():
        hub_coords[int(row["h_idx"])] = transformer.transform(
            float(row["longitude"]),
            float(row["latitude"]),
        )

    existing_pairs = {
        tuple(sorted((int(row["hub_a_h_idx"]), int(row["hub_b_h_idx"]))))
        for _, row in links_df.iterrows()
    }
    flow_threshold = links_df["flow_intensity"].quantile(
        FLOW_SUPPLEMENT_THRESHOLD_PERCENTILE / 100
    )

    candidate_additions = []
    for h_a, h_b in combinations(hubs_df["h_idx"].astype(int).values, 2):
        pair = tuple(sorted((int(h_a), int(h_b))))
        if pair in existing_pairs:
            continue

        xa, ya = hub_coords[int(h_a)]
        xb, yb = hub_coords[int(h_b)]
        dist_miles = float(np.hypot(xa - xb, ya - yb) / 1609.34)
        if dist_miles > MAX_LINK_MILES:
            continue

        flow = compute_hub_pair_flow(int(h_a), int(h_b), hub_lookup, flow_lookup)
        if flow < flow_threshold:
            continue

        row_a = hub_meta.loc[int(h_a)]
        row_b = hub_meta.loc[int(h_b)]
        candidate_additions.append(
            {
                "hub_a_h_idx": int(h_a),
                "hub_b_h_idx": int(h_b),
                "hub_a_candidate_id": row_a["candidate_id"],
                "hub_b_candidate_id": row_b["candidate_id"],
                "hub_a_name": row_a["facility_name"],
                "hub_b_name": row_b["facility_name"],
                "hub_a_state": row_a["source_state"],
                "hub_b_state": row_b["source_state"],
                "distance_miles": round(dist_miles, 3),
                "drive_time_h": round(dist_miles / 55.0, 3),
                "shared_region": False,
                "flow_intensity": flow,
            }
        )

    additions_df = pd.DataFrame(candidate_additions)
    print(
        "  High-flow supplement threshold: "
        f"{flow_threshold:,.0f} thousand tons"
    )
    print(f"  Added links: {len(additions_df)}")

    print("\n[6/6] Saving final flow-weighted network")
    final_links = pd.concat([kept_links, additions_df], ignore_index=True)
    final_links = final_links.sort_values(
        ["flow_intensity", "distance_miles"], ascending=[False, True]
    ).reset_index(drop=True)

    final_links.to_csv(FLOW_LINK_PATH, index=False)
    print(f"  Saved: {FLOW_LINK_PATH}")
    print(f"  Final links: {len(final_links)}")
    print(
        "  Flow intensity: "
        f"min={final_links['flow_intensity'].min():,.0f}, "
        f"mean={final_links['flow_intensity'].mean():,.0f}, "
        f"max={final_links['flow_intensity'].max():,.0f} thousand tons"
    )


if __name__ == "__main__":
    main()
